### PR TITLE
for loop initial declarations are only allowed in C99 mode

### PR DESCRIPTION
**Pull request by marguerite**

### CODE REVIEW

**Comment by wengxt** [comment]
Well.. can we just force C99 instead in cmake?.. are you having a issue with a compiler that can't do C99?

**Comment by marguerite** [comment]
@wengxt the problem, it also has some usages only available under `-std=c++11`, eg: `QString name() override;` (warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default])

**Comment by marguerite** [comment]
@wengxt any updates?

**Comment by marguerite** [comment]
@wengxt I mean, does "QString name() override" work with C99? This is also in the current fcitx codes. If they don't work with C99, then such a simple global change will not be possible.

**Comment by yuyichao** [comment]
C++ mode is independent of C mode.

**Comment by yuyichao** [comment]
And FWIW since C++11 is required, I don't know any compiler that can support C++11 in C++ mode but not C99 in C mode. (IIRC even MSVC support most C99 now....)

**Comment by wengxt** [comment]
Well, this repo has only c code, why would you bother c++? Adding lines above won't affect other repo.

**Comment by marguerite** [comment]
...then yes...

**Comment by marguerite** [comment]
Just let me have a check...to see if I opened the wrong build log (maybe I just opened the build log of fcitx-libpinyin)...

**Comment by wengxt** [comment]
@yuyichao I don't test centos or similar distro nowadays.. but I know systemd force c99 in their code, so any distro using systemd would at least support c99

**Comment by marguerite** [comment]
Yes I took the wrong build log (twice!)...so C99 is okay to me, all openSUSE releases supported do support C99.

**Pull request closed without merging**
